owner: JEngrob
repo: Randers-uptime

# Overvågede sider i ønsket rækkefølge
sites:
  - name: Randers.dk
    url: https://www.randers.dk
    slug: randers-dk

  - name: Skolernes Udviklingscenter
    url: https://skolernesudviklingscenter.randers.dk/da/soeg
    slug: skolernesudviklingscenter-randers-dk

  - name: Nordbyen Kalder
    url: https://nordbyenkalder.randers.dk/soeg
    slug: nordbyenkalder-randers-dk

  - name: Sprogcenter Randers
    url: https://sprogcenter.randers.dk/soeg
    slug: sprogcenter-randers-dk

  - name: Børnehuset Mælkevejen
    url: https://www.museumoj.dk
    slug: museumoj.dk


status-website:
  baseUrl: /Randers-uptime
  cname: false
  logoUrl: https://www.randers.dk/media/o0zlm1pt/randers_kommune_logo.svg
  name: Driftstatus – Randers Kommune
  introTitle: Driftstatus for Randers Kommunes vigtigste sider
  introMessage: >
    Her kan du følge driftsstatus på Randers.dk og tilhørende subsites.
    Opdateres automatisk hvert 5. minut.
  navbar:
    - title: Forside
      href: /
    - title: Historik
      href: /history
    - title: API
      href: /api

# Dansk UI
i18n:
  liveStatus: Live status
  allSystemsOperational: Alle systemer kører normalt
  responseTime: Responstid
  incidents: Hændelser
  incidentHistory: Historik
  activeIncidents: Aktive hændelser
  pastIncidents: Tidligere hændelser
  degraded: Nedsat
  down: Nede
  up: Oppe

checks:
  frequency: 5
  maxResponseTime: 60000

deployments:
  commitsPerPage: 30
  timezone: Europe/Copenhagen

# Randers.dk styling + mobilvenlighed
theme:
  status-website:
    theme: light
    customCss: |
      body {
        background: #F5F7F8 !important;
        color: #2A2A2A !important;
        font-family: "Roboto", Arial, sans-serif !important;
      }
      a {
        color: #00457C !important;
      }
      header {
        background: #00457C !important;
        color: white !important;
        padding: 14px 20px !important;
      }
      header a {
        color: white !important;
      }
      .status {
        border-radius: 10px !important;
      }
      @media (max-width: 600px) {
        .status {
          flex-direction: column !important;
        }
      }
