owner: JEngrob
repo: Randers-uptime

sites:
  - name: Randers.dk
    url: https://www.randers.dk
    slug: randers-dk

  - name: Valg.randers.dk
    url: https://valg.randers.dk
    slug: valg-randers-dk

status-website:
  cname: false
  logoUrl: https://www.randers.dk/media/o0zlm1pt/randers_kommune_logo.svg
  name: Randers Kommune – Driftstatus
  introTitle: Driftstatus for Randers Kommunes vigtigste sider
  introMessage: >
    Her kan du følge driftsstatus for Randers.dk og Valg.randers.dk.
    Status opdateres automatisk hvert 5. minut.

notifications:
  slack: false
  telegram: false
  webhook: false
  email: false

checks:
  frequency: 5
  maxResponseTime: 60000

deployments:
  commitsPerPage: 30
  timezone: Europe/Copenhagen

theme:
  status-website:
    defaultLanguage: en
